from django.urls import path
from .views import (BeneficiaryListView,
                    BeneficiaryRequestCreateView,
                    BeneficiaryDetailView,
                    BeneficiaryRequestHistoryCreate,
                    BeneficiaryRequestChildCreate,
                    BeneficiaryAllRequestsView,
                    BeneficiaryRequestOnetimeCreationView,
                    BeneficiaryRequestRecurringCreationView,
                    BeneficiaryNewRequestGetView,
                    BeneficiaryOldRequestOnetimeGetView,
                    BeneficiaryOldRequestOngoingGetView,
                    SingleRequestGetView,
                    BeneficiaryUpdateRequestView,
                    SingleHistoryUpdateView,
                    SingleChildUpdateView,
                    SingleOnetimeUpdateView,
                    SingleRecurringUpdateView,
                    ChangeRequestProcessingStageView,
                    UpdateBeneficiaryAdditionalInfoView,
                    UpdateBeneficiaryAddressView,
                    UpdateBeneficiaryInformationView,
                    BeneficiaryRequestAnnouncementListView,
                    BeneficiaryRequestAnnouncementCreateView,
                    BeneficiaryRequestAnnouncementUpdateView,
                    BeneficiaryAnnouncementListView,
                    BeneficiaryAnnouncementCreateView,
                    BeneficiaryAnnouncementUpdateView,
                    SingleRequestChildsView,
                    SingleRequestHistoriesView,
                    SingleBeneficiaryAllRequestsView,
                    AllRequestChildsView,
                    BeneficiaryRequestTypeLayer1View,
                    BeneficiaryRequestTypeLayer2View,
                    BeneficiaryRequestProcessingStageView,
                    BeneficiaryRequestDurationLookupView,
                    ProvinceLookupView,
                    CityLookupView,
                    ChangeChildRequestProcessingStage,
                    CreateBeneficiary,
                    CreateBeneficiaryInformation,
                    DeleteBeneficiaryInformation,
                    UpdateBeneficiaryUserRegistration,
                    CreateAddress,
                    CreateAdditionalInfo,
                    )
from user.api.views import (BeneficiaryRegisterView,)

urlpatterns = [
    path('beneficiaries/list/', BeneficiaryListView.as_view(), name='beneficiary-list'),
    path('beneficiaries/create/',BeneficiaryRegisterView.as_view(), name='create-beneficiary'),
    path('beneficiaries/<int:pk>/update-register/',UpdateBeneficiaryUserRegistration.as_view(),name='update-register'),
    path('beneficiaries/<int:pk>/create-information/',CreateBeneficiaryInformation.as_view(), name="create-user-information"),
    path('beneficiaries/<int:pk>/delete-information/',DeleteBeneficiaryInformation.as_view(), name="delete-user-information"),
    path('beneficiaries/<int:pk>/update-information/',UpdateBeneficiaryInformationView.as_view(), name="update-user-information"),
    path('beneficiaries/<int:pk>/request-create/', BeneficiaryRequestCreateView.as_view(), name='beneficiary-request-create'),
    path('beneficiaries/<int:pk>/get/', BeneficiaryDetailView.as_view(), name='beneficiary-detail'),
    path('beneficiaries/<int:pk>/get-requests/', SingleBeneficiaryAllRequestsView.as_view(), name='beneficiary-get-requests'),
    path('beneficiaries/<int:pk>/create-address/', CreateAddress.as_view(), name="create-address"),
    path('beneficiaries/<int:pk>/update-address/', UpdateBeneficiaryAddressView.as_view(), name='beneficiary-update-address'),
    path('beneficiaries/<int:pk>/create-additional-info/', CreateAdditionalInfo.as_view(),name="create-additional-info"),
    path('beneficiaries/<int:pk>/update-additional-info/', UpdateBeneficiaryAdditionalInfoView.as_view(), name='beneficiary-update-additional-info'),
    path('beneficiaries/<int:pk>/announcement/list/', BeneficiaryAnnouncementListView.as_view(), name='beneficiary-announcement-list'),
    path('beneficiaries/<int:pk>/announcement/create/', BeneficiaryAnnouncementCreateView.as_view(), name='beneficiary-announcement-create'),
    path('requests/<int:pk>/get/', SingleRequestGetView.as_view(), name='beneficiary-request-get'),
    path('requests/<int:pk>/update/', BeneficiaryUpdateRequestView.as_view(), name='beneficiary-request-update'),
    path('requests/<int:pk>/create-history/', BeneficiaryRequestHistoryCreate.as_view(), name='beneficiary-request-history-create'),
    path('requests/<int:pk>/create-child/', BeneficiaryRequestChildCreate.as_view(), name='beneficiary-request-child-create'),
    path('requests/childs/', AllRequestChildsView.as_view(), name='beneficiary-request-childs'),
    path('requests/<int:pk>/childs/', SingleRequestChildsView.as_view(), name='beneficiary-request-childs'),
    path('requests/<int:pk>/histories/', SingleRequestHistoriesView.as_view(), name='beneficiary-request-histories'),
    path('requests/list/', BeneficiaryAllRequestsView.as_view(), name='beneficiary-all-requests'),
    path('requests/<int:pk>/create-onetime/', BeneficiaryRequestOnetimeCreationView.as_view(), name='beneficiary-request-onetime-create'),
    path('requests/<int:pk>/create-recurring/', BeneficiaryRequestRecurringCreationView.as_view(), name='beneficiary-request-recurring-create'),
    path('requests/new-requests/', BeneficiaryNewRequestGetView.as_view(), name='beneficiary-new-requests-get'),
    path('requests/old-onetime-requests/', BeneficiaryOldRequestOnetimeGetView.as_view(), name='beneficiary-old-onetime-requests-get'),
    path('requests/old-ongoing-requests/', BeneficiaryOldRequestOngoingGetView.as_view(), name='beneficiary-old-ongoing-requests-get'),
    path('requests/history/<int:pk>/update/', SingleHistoryUpdateView.as_view(), name='beneficiary-request-history-update'),
    path('requests/child/<int:pk>/update/', SingleChildUpdateView.as_view(), name='beneficiary-request-child-update'),
    path('requests/recurring/<int:pk>/update/', SingleRecurringUpdateView.as_view(), name='beneficiary-request-recurring-update'),
    path('requests/onetime/<int:pk>/update/', SingleOnetimeUpdateView.as_view(), name='beneficiary-request-onetime-update'),
    path('requests/<int:pk>/change-processing-stage/', ChangeRequestProcessingStageView.as_view(), name='beneficiary-request-change-processing-stage'),
    path('requests/childs/<int:pk>/change-processing-stage/', ChangeChildRequestProcessingStage.as_view(), name='beneficiary-request-child-change-processing-stage'),
    path('requests/<int:pk>/announcement/list/', BeneficiaryRequestAnnouncementListView.as_view(), name='beneficiary-request-announcement-list'),
    path('requests/<int:pk>/announcement/create/', BeneficiaryRequestAnnouncementCreateView.as_view(), name='beneficiary-request-announcement-create'),
    path('request-announcement/<int:pk>/update/', BeneficiaryRequestAnnouncementUpdateView.as_view(), name='beneficiary-request-announcement-update'),
    path('announcement/<int:pk>/update/', BeneficiaryAnnouncementUpdateView.as_view(), name='beneficiary-announcement-update'),

    #lookup request fields
    path('requests/type-layer1/', BeneficiaryRequestTypeLayer1View.as_view(), name="type-layer1"),
    path('requests/type-layer2/', BeneficiaryRequestTypeLayer2View.as_view(), name="type-layer2"),
    path('requests/processing-stage/', BeneficiaryRequestProcessingStageView.as_view(), name="processing-stage"),
    path('requests/duration/', BeneficiaryRequestDurationLookupView.as_view(), name="duration"),
    path('provinces/',ProvinceLookupView.as_view(), name='provinces'),
    path('cities/', CityLookupView.as_view(), name='cities'),

]