from django.urls import path
from .views import (BeneficiaryListView,
                    BeneficiaryRequestCreateView,
                    BeneficiaryDetailView,
                    BeneficiaryRequestHistoryCreate,
                    BeneficiaryRequestChildCreate,
                    BeneficiaryAllRequestsView,
                    BeneficiaryRequestOnetimeCreationView,
                    BeneficiaryRequestRecurringCreationView,
                    BeneficiaryNewRequestGetView,
                    BeneficiaryOldRequestOnetimeGetView,
                    BeneficiaryOldRequestOngoingGetView,
                    SingleRequestGetView,
                    BeneficiaryUpdateRequestView,
                    SingleHistoryUpdateView,
                    SingleChildUpdateView,
                    SingleOnetimeUpdateView,
                    SingleRecurringUpdateView,
                    ChangeRequestProcessingStageView,
                    UpdateBeneficiaryAdditionalInfoView,
                    UpdateBeneficiaryAddressView,
                    UpdateBeneficiaryInformationView,
                    BeneficiaryRequestAnnouncementListView,
                    BeneficiaryRequestAnnouncementCreateView,
                    BeneficiaryRequestAnnouncementUpdateView)

urlpatterns = [
    path('beneficiaries/list/', BeneficiaryListView.as_view(), name='beneficiary-list'),
    path('beneficiaries/request-create/', BeneficiaryRequestCreateView.as_view(), name='beneficiary-request-create'),
    path('beneficiaries/<int:pk>/get/', BeneficiaryDetailView.as_view(), name='beneficiary-detail'),
    path('beneficiaries/<int:pk>/update-information/', UpdateBeneficiaryInformationView.as_view(), name='beneficiary-update-information'),
    path('beneficiaries/<int:pk>/update-address/', UpdateBeneficiaryAddressView.as_view(), name='beneficiary-update-address'),
    path('beneficiaries/<int:pk>/update-additional-info/', UpdateBeneficiaryAdditionalInfoView.as_view(), name='beneficiary-update-additional-info'),
    path('requests/<int:pk>/get/', SingleRequestGetView.as_view(), name='beneficiary-request-get'),
    path('requests/<int:pk>/update/', BeneficiaryUpdateRequestView.as_view(), name='beneficiary-request-update'),
    path('requests/<int:pk>/create-history/', BeneficiaryRequestHistoryCreate.as_view(), name='beneficiary-request-history-create'),
    path('requests/<int:pk>/create-child/', BeneficiaryRequestChildCreate.as_view(), name='beneficiary-request-child-create'),
    path('requests/list/', BeneficiaryAllRequestsView.as_view(), name='beneficiary-all-requests'),
    path('requests/<int:pk>/create-onetime/', BeneficiaryRequestOnetimeCreationView.as_view(), name='beneficiary-request-onetime-create'),
    path('requests/<int:pk>/create-recurring/', BeneficiaryRequestRecurringCreationView.as_view(), name='beneficiary-request-recurring-create'),
    path('requests/new-requests/', BeneficiaryNewRequestGetView.as_view(), name='beneficiary-new-requests-get'),
    path('requests/old-onetime-requests/', BeneficiaryOldRequestOnetimeGetView.as_view(), name='beneficiary-old-onetime-requests-get'),
    path('requests/old-ongoing-requests/', BeneficiaryOldRequestOngoingGetView.as_view(), name='beneficiary-old-ongoing-requests-get'),
    path('requests/history/<int:pk>/update/', SingleHistoryUpdateView.as_view(), name='beneficiary-request-history-update'),
    path('requests/child/<int:pk>/update/', SingleChildUpdateView.as_view(), name='beneficiary-request-child-update'),
    path('requests/recurring/<int:pk>/update/', SingleRecurringUpdateView.as_view(), name='beneficiary-request-recurring-update'),
    path('requests/onetime/<int:pk>/update/', SingleOnetimeUpdateView.as_view(), name='beneficiary-request-onetime-update'),
    path('requests/<int:pk>/change-processing-stage/', ChangeRequestProcessingStageView.as_view(), name='beneficiary-request-change-processing-stage'),
    path('requests/<int:pk>/announcement/list/', BeneficiaryRequestAnnouncementListView.as_view(), name='beneficiary-request-announcement-list'),
    path('requests/<int:pk>/announcement/create/', BeneficiaryRequestAnnouncementCreateView.as_view(), name='beneficiary-request-announcement-create'),
    path('request-announcement/<int:pk>/update/', BeneficiaryRequestAnnouncementUpdateView.as_view(), name='beneficiary-request-announcement-update'),
]