# Generated by Django 5.2 on 2025-04-13 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('charity_id', models.AutoField(primary_key=True, serialize=False)),
                ('charity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('charity_username', models.CharField(max_length=255)),
                ('charity_password', models.CharField(max_length=255)),
                ('charity_phone_number', models.IntegerField(blank=True, null=True)),
                ('charity_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('charity_created_at', models.DateTimeField(auto_now_add=True)),
                ('charity_updated_at', models.DateTimeField(auto_now=True)),
                ('charity_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
