from .views import (BeneficiaryUserView,
                    BeneficiaryRequestView,
                    BeneficiaryRequestOnetimeCreationView,
                    BeneficiaryRequestRecurringCreationView,
                    BeneficiaryRequestInitialStagesGetView,
                    BeneficiaryRequestInProgressGetView,
                    BeneficiaryRequestCompletedGetView,
                    BeneficiaryRequestRejectedGetView,
                    BenefeciarySingleRequestGetView,
                    BeneficiaryUpdateSingleRequestView,
                    BeneficiaryUpdateOnetimeView,
                    BeneficiaryUpdateRecurringView,
                    BeneficiarySingleRequestChildsGetView,
                    BeneficiarySingleChildGetView,
                    BeneficiaryChildCreateView,
                    BeneficiarySingleChildUpdateView,
                    BeneficiaryRequestHistoriesGetView,
                    BeneficiarySingleHistoryGetView,
                    AnnouncementView,
                    AnnouncementRequestView,)
from django.urls import path

urlpatterns = [
    path('beneficiary/<int:pk>/information/', BeneficiaryUserView.as_view(), name='beneficiary_information'),
    path('beneficiary/<int:pk>/request-create/', BeneficiaryRequestView.as_view(), name='beneficiary_request_create'),
    path('beneficiary/<int:pk>/request-create-onetime/<int:request_pk>/', BeneficiaryRequestOnetimeCreationView.as_view(), name='beneficiary_request_create_onetime'),
    path('beneficiary/<int:pk>/request-create-recurring/<int:request_pk>/', BeneficiaryRequestRecurringCreationView.as_view(), name='beneficiary_request_create_recurring'),
    path('beneficiary/<int:pk>/request-initial-stages-get/', BeneficiaryRequestInitialStagesGetView.as_view(), name='beneficiary_request_initial_stages_get'),
    path('beneficiary/<int:pk>/request-in-progress-get/', BeneficiaryRequestInProgressGetView.as_view(), name='beneficiary_request_in_progress_get'),
    path('beneficiary/<int:pk>/request-completed-get/', BeneficiaryRequestCompletedGetView.as_view(), name='beneficiary_request_completed_get'),
    path('beneficiary/<int:pk>/request-rejected-get/', BeneficiaryRequestRejectedGetView.as_view(), name='beneficiary_request_rejected_get'),
    path('beneficiary/<int:pk>/request-single-get/<int:request_pk>/', BenefeciarySingleRequestGetView.as_view(), name='beneficiary_single_request_get'),
    path('beneficiary/<int:pk>/request-single-update/<int:request_pk>/', BeneficiaryUpdateSingleRequestView.as_view(), name='beneficiary_single_request_update'),
    path('beneficiary/<int:pk>/request-single-update-onetime/<int:request_pk>/', BeneficiaryUpdateOnetimeView.as_view(), name='beneficiary_single_request_update_onetime'),
    path('beneficiary/<int:pk>/request-single-update-recurring/<int:request_pk>/', BeneficiaryUpdateRecurringView.as_view(), name='beneficiary_single_request_update_recurring'),
    path('beneficiary/<int:pk>/request-childs-get/<int:request_pk>/', BeneficiarySingleRequestChildsGetView.as_view(), name='beneficiary_single_request_childs_get'),
    path('beneficiary/<int:pk>/request-single-child-get/<int:request_pk>/', BeneficiarySingleChildGetView.as_view(), name='beneficiary_single_child_get'),
    path('beneficiary/<int:pk>/request-child-create/<int:request_pk>/', BeneficiaryChildCreateView.as_view(), name='beneficiary_child_create'),
    path('beneficiary/<int:pk>/request-single-child-update/<int:request_pk>/', BeneficiarySingleChildUpdateView.as_view(), name='beneficiary_single_child_update'),
    path('beneficiary/<int:pk>/request-histories-get/<int:request_pk>/', BeneficiaryRequestHistoriesGetView.as_view(), name='beneficiary_request_histories_get'),
    path('beneficiary/<int:pk>/request-single-history-get/<int:request_pk>/', BeneficiarySingleHistoryGetView.as_view(), name='beneficiary_single_history_get'),
    path('beneficiary/<int:pk>/announcement-get/', AnnouncementView.as_view(), name='beneficiary_request_announcement_get'),
    path('beneficiary/<int:pk>/request-announcement-get/<int:request_pk>/', AnnouncementRequestView.as_view(), name='beneficiary_request_announcement_request_get'),

    
]