# Generated by Django 5.2 on 2025-04-13 11:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiary', '0001_initial'),
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryRequestDuration',
            fields=[
                ('beneficiary_request_duration_id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_request_duration_name', models.CharField(choices=[('one_time', 'One Time'), ('recurring', 'Recurring'), ('permanent', 'Permanent')], max_length=10, unique=True)),
                ('beneficiary_request_duration_created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_request_duration_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryRequestProcessingStage',
            fields=[
                ('beneficiary_request_processing_stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_request_processing_stage_name', models.CharField(choices=[('submitted', 'Submitted'), ('pending_review', 'Pending Review'), ('under_evaluation', 'Under Evaluation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20, unique=True)),
                ('beneficiary_request_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=8, unique=True)),
                ('beneficiary_request_processing_stage_created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_request_processing_stage_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryRequestTypeLayer1',
            fields=[
                ('beneficiary_request_type_layer1_id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_request_type_layer1_name', models.CharField(choices=[('good', 'Good'), ('cash', 'Cash'), ('service', 'Service')], max_length=10, unique=True)),
                ('beneficiary_request_type_layer1_created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_request_type_layer1_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryRequest',
            fields=[
                ('beneficiary_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_request_title', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_request_description', models.TextField(blank=True, null=True)),
                ('beneficiary_request_document', models.FileField(blank=True, null=True, upload_to='request_docs/')),
                ('beneficiary_request_date', models.DateField(blank=True, null=True)),
                ('beneficiary_request_time', models.TimeField(blank=True, null=True)),
                ('beneficiary_request_created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_request_updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_user_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiary.beneficiaryuserregistration')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.charity')),
                ('beneficiary_request_duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='request.beneficiaryrequestduration')),
                ('beneficiary_request_processing_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.beneficiaryrequestprocessingstage')),
                ('beneficiary_request_type_layer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.beneficiaryrequesttypelayer1')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryRequestDurationOnetime',
            fields=[
                ('beneficiary_request_duration_onetime_id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_request_duration_onetime_deadline', models.DateField()),
                ('beneficiary_request_duration_onetime_created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_request_duration_onetime_updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.beneficiaryrequest')),
                ('beneficiary_request_duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.beneficiaryrequestduration')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryRequestDurationRecurring',
            fields=[
                ('beneficiary_request_duration_recurring_id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_request_duration_recurring_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('beneficiary_request_duration_recurring_created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_request_duration_recurring_updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.beneficiaryrequest')),
                ('beneficiary_request_duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.beneficiaryrequestduration')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryRequestHistory',
            fields=[
                ('beneficiary_request_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_request_history_title', models.CharField(max_length=255)),
                ('beneficiary_request_history_description', models.TextField()),
                ('beneficiary_request_history_document', models.FileField(blank=True, null=True, upload_to='history_docs/')),
                ('beneficiary_request_history_date', models.DateField(blank=True, null=True)),
                ('beneficiary_request_history_time', models.TimeField(blank=True, null=True)),
                ('beneficiary_request_history_created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_request_history_updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.beneficiaryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryRequestChild',
            fields=[
                ('beneficiary_request_child_id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_request_child_description', models.TextField()),
                ('beneficiary_request_child_document', models.FileField(blank=True, null=True, upload_to='child_docs/')),
                ('beneficiary_request_child_date', models.DateField(blank=True, null=True)),
                ('beneficiary_request_child_time', models.TimeField(blank=True, null=True)),
                ('beneficiary_request_child_created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_request_child_updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.beneficiaryrequest')),
                ('beneficiary_request_child_processing_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.beneficiaryrequestprocessingstage')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryRequestTypeLayer2',
            fields=[
                ('beneficiary_request_type_layer2_id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_request_type_layer2_name', models.CharField(max_length=255, unique=True)),
                ('beneficiary_request_type_layer2_created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_request_type_layer2_updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_request_type_layer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.beneficiaryrequesttypelayer1')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiaryrequest',
            name='beneficiary_request_type_layer2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.beneficiaryrequesttypelayer2'),
        ),
        migrations.CreateModel(
            name='CharityAnnouncementForRequest',
            fields=[
                ('charity_announcement_for_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('charity_announcement_for_request_title', models.CharField(max_length=255)),
                ('charity_announcement_for_request_description', models.TextField(blank=True, null=True)),
                ('charity_announcement_for_request_created_at', models.DateTimeField(auto_now_add=True)),
                ('charity_announcement_for_request_updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.beneficiaryrequest')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.charity')),
            ],
        ),
        migrations.CreateModel(
            name='CharityWorkfield',
            fields=[
                ('charity_workfield_id', models.AutoField(primary_key=True, serialize=False)),
                ('charity_workfield_title', models.CharField(max_length=255)),
                ('charity_workfield_description', models.TextField(blank=True, null=True)),
                ('charity_workfield_created_at', models.DateTimeField(auto_now_add=True)),
                ('charity_workfield_updated_at', models.DateTimeField(auto_now=True)),
                ('charity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.charity')),
            ],
        ),
    ]
