# Generated by Django 5.2 on 2025-04-15 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_charityworkfield_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryrequest',
            name='beneficiary_request_duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='request.beneficiaryrequestduration'),
        ),
        migrations.AlterField(
            model_name='beneficiaryrequest',
            name='beneficiary_request_type_layer1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.beneficiaryrequesttypelayer1'),
        ),
        migrations.AlterField(
            model_name='beneficiaryrequest',
            name='beneficiary_request_type_layer2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.beneficiaryrequesttypelayer2'),
        ),
    ]
