# Generated by Django 5.2 on 2025-04-16 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0006_alter_beneficiaryuseradditionalinfo_beneficiary_user_registration_and_more'),
        ('request', '0004_alter_beneficiaryrequestprocessingstage_beneficiary_request_processing_stage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryrequest',
            name='beneficiary_user_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_requests', to='beneficiary.beneficiaryuserregistration'),
        ),
    ]
