# Generated by Django 5.2 on 2025-04-16 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_alter_beneficiaryrequest_beneficiary_user_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryrequestchild',
            name='beneficiary_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_request_child', to='request.beneficiaryrequest'),
        ),
        migrations.AlterField(
            model_name='beneficiaryrequesthistory',
            name='beneficiary_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_request_history', to='request.beneficiaryrequest'),
        ),
    ]
