# Generated by Django 5.2 on 2025-04-16 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_alter_beneficiaryrequestchild_beneficiary_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryrequestdurationonetime',
            name='beneficiary_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_request_duration_onetime', to='request.beneficiaryrequest'),
        ),
        migrations.AlterField(
            model_name='beneficiaryrequestdurationrecurring',
            name='beneficiary_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_request_duration_recurring', to='request.beneficiaryrequest'),
        ),
    ]
