# Generated by Django 5.2 on 2025-04-19 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_alter_beneficiaryrequestdurationonetime_beneficiary_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityannouncementforrequest',
            name='beneficiary_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_request_announcement', to='request.beneficiaryrequest'),
        ),
    ]
