# Generated by Django 5.2 on 2025-04-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_alter_charityannouncementforrequest_beneficiary_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charityannouncementforrequest',
            name='charity',
        ),
    ]
