# Generated by Django 5.2 on 2025-04-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_remove_charityannouncementforrequest_charity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaryrequest',
            name='charity',
        ),
    ]
