# Generated by Django 5.2 on 2025-04-29 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_remove_beneficiaryrequest_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryrequest',
            name='beneficiary_request_created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryrequest',
            name='beneficiary_request_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryrequestdurationonetime',
            name='beneficiary_request_duration_onetime_deadline',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryrequestdurationrecurring',
            name='beneficiary_request_duration_recurring_limit',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
