# Generated by Django 5.2 on 2025-05-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0012_beneficiaryrequest_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryrequest',
            name='beneficiary_request_amount',
            field=models.PositiveBigIntegerField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='beneficiaryrequestchild',
            name='beneficiary_request_child_amount',
            field=models.PositiveBigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='beneficiaryrequesthistory',
            name='beneficiaty_request_history_amount',
            field=models.PositiveBigIntegerField(default=None),
        ),
    ]
