# Generated by Django 5.2 on 2025-05-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_beneficiaryrequest_beneficiary_request_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityannouncementforrequest',
            name='charity_announcement_for_request_seen',
            field=models.BooleanField(default=False),
        ),
    ]
