# Generated by Django 5.2 on 2025-05-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0014_charityannouncementforrequest_charity_announcement_for_request_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryrequest',
            name='beneficiary_request_is_created_by_charity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiaryrequestchild',
            name='beneficiary_request_child_is_created_by_charity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiaryrequestdurationonetime',
            name='beneficiary_request_duration_onetime_is_created_by_charity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiaryrequestdurationrecurring',
            name='beneficiary_request_duration_recurring_is_created_by_charity',
            field=models.BooleanField(default=False),
        ),
    ]
