# Generated by Django 5.2 on 2025-05-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0015_beneficiaryrequest_beneficiary_request_is_created_by_charity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryrequest',
            name='beneficiary_request_amount',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryrequestchild',
            name='beneficiary_request_child_amount',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryrequesthistory',
            name='beneficiaty_request_history_amount',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
    ]
