# Generated by Django 5.2 on 2025-04-13 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=255, unique=True)),
                ('province_created_at', models.DateTimeField(auto_now_add=True)),
                ('province_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryUserRegistration',
            fields=[
                ('beneficiary_user_registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('identification_number', models.IntegerField(unique=True)),
                ('beneficiary_id', models.IntegerField(unique=True)),
                ('phone_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_user_registration_created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_user_registration_updated_at', models.DateTimeField(auto_now=True)),
                ('benficiary_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.charity')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryUserInformation',
            fields=[
                ('beneficiary_user_information_id', models.AutoField(primary_key=True, serialize=False)),
                ('under_charity_support', models.BooleanField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('beneficiary_user_information_created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_user_information_updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_user_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiary.beneficiaryuserregistration')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryUserAdditionalInfo',
            fields=[
                ('beneficiary_user_additional_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_user_additional_info_title', models.CharField(max_length=255)),
                ('beneficiary_user_additional_info_description', models.TextField(blank=True, null=True)),
                ('beneficiary_user_additional_info_document', models.FileField(blank=True, null=True, upload_to='beneficiary_docs/')),
                ('beneficiary_user_additional_info_created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_user_additional_info_updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_user_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiary.beneficiaryuserregistration')),
            ],
        ),
        migrations.CreateModel(
            name='CharityAnnouncementToBeneficiary',
            fields=[
                ('charity_announcement_to_beneficiary_id', models.AutoField(primary_key=True, serialize=False)),
                ('charity_announcement_to_beneficiary_title', models.CharField(max_length=255)),
                ('charity_announcement_to_beneficiary_description', models.TextField(blank=True, null=True)),
                ('charity_announcement_to_beneficiary_created_at', models.DateTimeField(auto_now_add=True)),
                ('charity_announcement_to_beneficiary_updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_user_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiary.beneficiaryuserregistration')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.charity')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('city_created_at', models.DateTimeField(auto_now_add=True)),
                ('city_updated_at', models.DateTimeField(auto_now=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiary.province')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryUserAddress',
            fields=[
                ('beneficiary_user_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('neighborhood', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('alley', models.CharField(blank=True, max_length=255, null=True)),
                ('building_number', models.IntegerField(blank=True, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('beneficiary_user_address_created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_user_address_updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_user_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiary.beneficiaryuserinformation')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiary.city')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiary.province')),
            ],
        ),
    ]
