# Generated by Django 5.2 on 2025-04-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryuserregistration',
            name='beneficiary_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryuserregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
