# Generated by Django 5.2 on 2025-04-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0002_alter_beneficiaryuserregistration_beneficiary_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryuserregistration',
            name='identification_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
