# Generated by Django 5.2 on 2025-04-15 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0003_alter_beneficiaryuserregistration_identification_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaryuseraddress',
            name='beneficiary_user_information',
        ),
        migrations.AddField(
            model_name='beneficiaryuseraddress',
            name='beneficiary_user_registration',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='beneficiary.beneficiaryuserregistration'),
            preserve_default=False,
        ),
    ]
