# Generated by Django 5.2 on 2025-04-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0004_remove_beneficiaryuseraddress_beneficiary_user_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryuseraddress',
            name='building_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryuseraddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryuseraddress',
            name='unit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
