# Generated by Django 5.2 on 2025-04-16 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0005_alter_beneficiaryuseraddress_building_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryuseradditionalinfo',
            name='beneficiary_user_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_user_additional_info', to='beneficiary.beneficiaryuserregistration'),
        ),
        migrations.AlterField(
            model_name='beneficiaryuseraddress',
            name='beneficiary_user_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_user_address', to='beneficiary.beneficiaryuserregistration'),
        ),
        migrations.AlterField(
            model_name='beneficiaryuserinformation',
            name='beneficiary_user_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_user_information', to='beneficiary.beneficiaryuserregistration'),
        ),
    ]
