# Generated by Django 5.2 on 2025-04-16 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0006_alter_beneficiaryuseradditionalinfo_beneficiary_user_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryuseraddress',
            name='beneficiary_user_registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_user_address', to='beneficiary.beneficiaryuserregistration'),
        ),
        migrations.AlterField(
            model_name='beneficiaryuserinformation',
            name='beneficiary_user_registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_user_information', to='beneficiary.beneficiaryuserregistration'),
        ),
    ]
