# Generated by Django 5.2 on 2025-04-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0007_alter_beneficiaryuseraddress_beneficiary_user_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charityannouncementtobeneficiary',
            name='charity',
        ),
    ]
