# Generated by Django 5.2 on 2025-04-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0008_remove_charityannouncementtobeneficiary_charity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaryuserregistration',
            name='charity',
        ),
    ]
