# Generated by Django 5.2 on 2025-04-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0009_remove_beneficiaryuserregistration_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryuseraddress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_city', to='beneficiary.city'),
        ),
        migrations.AlterField(
            model_name='beneficiaryuseraddress',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_province', to='beneficiary.province'),
        ),
    ]
