# Generated by Django 5.2 on 2025-04-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0010_alter_beneficiaryuseraddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryuseraddress',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryuserinformation',
            name='birth_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryuserinformation',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryuserinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], db_index=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryuserinformation',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryuserregistration',
            name='beneficiary_id',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryuserregistration',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryuserregistration',
            name='identification_number',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryuserregistration',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='province',
            name='province_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
