# Generated by Django 5.2 on 2025-05-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0011_alter_beneficiaryuseraddress_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityannouncementtobeneficiary',
            name='charity_announcement_to_beneficiary_seen',
            field=models.BooleanField(default=False),
        ),
    ]
