# Generated by Django 5.2 on 2025-05-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0012_charityannouncementtobeneficiary_charity_announcement_to_beneficiary_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryuseradditionalinfo',
            name='beneficiary_user_additional_info_is_created_by_charity',
            field=models.BooleanField(default=False),
        ),
    ]
