# Generated by Django 5.2 on 2025-07-08 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0013_beneficiaryuseradditionalinfo_beneficiary_user_additional_info_is_created_by_charity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryUserFamilyInfo',
            fields=[
                ('beneficiary_user_family_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_user_family_info_family_relation', models.CharField(choices=[('child', 'Child'), ('partner', 'Partner')], max_length=10)),
                ('beneficiary_user_family_info_identification_number', models.CharField(max_length=10, unique=True)),
                ('beneficiary_user_family_info_first_name', models.CharField(max_length=255)),
                ('beneficiary_user_family_info_last_name', models.CharField(max_length=255)),
                ('beneficiary_user_family_info_birth_date', models.DateField(blank=True, null=True)),
                ('beneficiary_user_family_info_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('beneficiary_user_family_info_created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_user_family_info_updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_user_registration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_user_family_info', to='beneficiary.beneficiaryuserregistration')),
            ],
        ),
    ]
